TRANSITLAND_DATASTORE_AUTH_TOKEN: iamallowedtotouchthis
ADMIN_USERNAME: onlyneedonproduction
ADMIN_PASSWORD: onlyneedonproduction
TRANSITLAND_DATASTORE_HOST: http://localhost:3000
AUTO_CONFLATE_STOPS_WITH_OSM: 'true'
MAX_HOURS_SINCE_LAST_CONFLATE: '84'
TYR_AUTH_TOKEN: 'get one from mapzen.com/developers'
ATTACHMENTS_S3_REGION: 'us-east-1'
ATTACHMENTS_S3_BUCKET: 'name of an S3 bucket'
AWS_ACCESS_KEY_ID: 'xxxxxxxxx'
AWS_SECRET_ACCESS_KEY: 'xxxxxx'
RUN_GOOGLE_FEEDVALIDATOR: 'false'
FEED_INFO_CACHE_EXPIRATION: '14400'
