---
:concurrency: 5
staging:
  :concurrency: 5
production:
  :concurrency: 5
:limits:
  feed_eater: 1
:process_limits:
  feed_eater_schedule: 1
:queues:
  - feed_eater
  - feed_eater_schedule
  - default
